apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shopedge.fullname" . }}-config
  labels:
    {{- include "shopedge.labels" . | nindent 4 }}
data:
  app-name: {{ .Values.config.appName | quote }}
  environment: {{ .Values.config.environment | quote }}
  app-version: {{ .Values.config.version | quote }}
  nginx.conf: |
    events {
        worker_connections 1024;
    }

    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        sendfile on;
        keepalive_timeout 65;

        server {
            listen 80;
            server_name localhost;

            location / {
                root /usr/share/nginx/html;
                index index.html;
                try_files $uri $uri/ =404;
            }

            location /health {
                access_log off;
                return 200 "healthy\n";
                add_header Content-Type text/plain;
            }
        }
    }