apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shopedge.fullname" . }}-secret
  labels:
    {{- include "shopedge.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.secret.apiKey | b64enc | quote }}
  database-url: {{ .Values.secret.databaseUrl | b64enc | quote }}